services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: db_convidados
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    restart: always
    depends_on:
      - db
    ports:
      - "${PORT:-8080}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_convidados
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MERCADO_PAGO_ACCESS_TOKEN: ${MERCADO_PAGO_ACCESS_TOKEN}
      MP_PUBLIC_KEY: ${MP_PUBLIC_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_EMAIL_FROM: ${RESEND_EMAIL_FROM}
      EMAIL_CASAL: ${EMAIL_CASAL}
    env_file:
      - .env

volumes:
  postgres_data:
